
export const PROFILE_LIST_REQUEST = "PROFILE_LIST_REQUEST";
export const PROFILE_LIST_SUCCESS = "PROFILE_LIST_SUCCESS";
export const PROFILE_LIST_FAIL = "PROFILE_LIST_FAIL";

export const PROFILE_DETAILS_REQUEST = "PROFILE_DETAILS_REQUEST";
export const PROFILE_DETAILS_SUCCESS = "PROFILE_DETAILS_SUCCESS";
export const PROFILE_DETAILS_FAIL = "PROFILE_DETAILS_FAIL";
